### ISSUE TITLE
Bot disconnects on its own

### ISSUE THREAD

**Issue by jung35** [jung35/ToyBot#10]
```
events.js:171
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:169:17)
    at WebSocketConnection.onError (/ToyBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/ToyBot/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:180:13)
    at WebSocket.finalize (/ToyBot/node_modules/ws/lib/websocket.js:185:12)
    at ClientRequest._req.on (/ToyBot/node_modules/ws/lib/websocket.js:635:10)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
```

**Comment by jung35** [comment]
Might have to do something with not catching logging? Can't seem to find reason why this is happening...
