### ISSUE TITLE
Another "Unhandled 'error' event"

### ISSUE THREAD

**Issue by jung35** [jung35/ToyBot#17]
```
events.js:171
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:169:17)
    at WebSocketConnection.onError (/root/ToyBot/node_modules/discord.js/src/cli                                                                                                                                                             ent/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/root/ToyBot/node_modules/ws/lib/event-target.js:128:1                                                                                                                                                             6)
    at WebSocket.emit (events.js:180:13)
    at _receiver.cleanup (/root/ToyBot/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/root/ToyBot/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/root/ToyBot/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by logyQT** [comment]
I have same problem with my bot for about 1 week

**Comment by Gwerbyn** [comment]
have you found a way to fix it because im having the same problem right now

**Comment by jung35** [comment]
I have no idea, sorry. Haven't touched the code for this bot in a while. Probably better off re-writing the entire code.

I'm just going to close this and everything since i stopped
